//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solutions.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solutions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Successfully connected to MS SQL Server..
        /// </summary>
        internal static string DbConnected {
            get {
                return ResourceManager.GetString("DbConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to connect to the MS SQL Server..
        /// </summary>
        internal static string DbConnectFailed {
            get {
                return ResourceManager.GetString("DbConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connecting to a MS SQL Server....
        /// </summary>
        internal static string DbConnecting {
            get {
                return ResourceManager.GetString("DbConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connected to the MS SQL Server..
        /// </summary>
        internal static string DbConnection {
            get {
                return ResourceManager.GetString("DbConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not connected to the MS SQL Server..
        /// </summary>
        internal static string DbConnectionNot {
            get {
                return ResourceManager.GetString("DbConnectionNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There is no connection to the database.
        ///Check the connection!.
        /// </summary>
        internal static string DbConnectionNotMsg {
            get {
                return ResourceManager.GetString("DbConnectionNotMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection error.
        /// </summary>
        internal static string DbConnectionNotMsgCaption {
            get {
                return ResourceManager.GetString("DbConnectionNotMsgCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have entered the name of the main component.
        ///Enter another name!.
        /// </summary>
        internal static string MsgDlgComponentName {
            get {
                return ResourceManager.GetString("MsgDlgComponentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The data was not uploaded!.
        /// </summary>
        internal static string MsgDlgDataNotLoaded {
            get {
                return ResourceManager.GetString("MsgDlgDataNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string MsgDlgErrorCaption {
            get {
                return ResourceManager.GetString("MsgDlgErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Info.
        /// </summary>
        internal static string MsgDlgInfoCaption {
            get {
                return ResourceManager.GetString("MsgDlgInfoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The remaining water that 
        ///can be used for the a component =&gt; {0}%.
        /// </summary>
        internal static string MsgDlgWater {
            get {
                return ResourceManager.GetString("MsgDlgWater", resourceCulture);
            }
        }
    }
}
